# Generated by Django 4.2.7 on 2023-12-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_is_published_blog_view_count_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
