# Generated by Django 4.2.7 on 2024-01-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_date_of_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': (('blog_custom_perm', 'модератор блога'),), 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
