# Generated by Django 4.2.7 on 2023-12-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contacts_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.products')),
            ],
            bases=('catalog.products',),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
