# Generated by Django 4.2.7 on 2023-12-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productinfo_delete_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInfo',
        ),
    ]
