# Generated by Django 4.2.7 on 2023-12-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя покупателя')),
                ('email', models.EmailField(max_length=150, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('closed', models.BooleanField(default=False, verbose_name='Заказ закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
